#!/bin/sh

# Exit build script on first failure.
set -e

# Exit on unset variable.
set -u

is_litestream_enabled() {
  set +ux

  local IS_ENABLED='false'

  if [[ ! -z "${LITESTREAM_ACCESS_KEY_ID}" ]] && \
      [[ ! -z "${LITESTREAM_SECRET_ACCESS_KEY}" ]]; then
    IS_ENABLED='true';
  fi

  set -ux

  echo "${IS_ENABLED}"
}

readonly IS_LITESTREAM_ENABLED="$(is_litestream_enabled)"

# Echo commands to stdout.
set -x

if [[ "${IS_LITESTREAM_ENABLED}" == 'true' ]]; then

  export readonly DB_PATH="/usr/app/data/noco.db"

  # Restore database from S3.
  /usr/src/app/litestream restore -if-replica-exists -v "${DB_PATH}"

  # Let Litestream start LogPaste as a child process
  /usr/src/app/litestream replicate \
      -exec "/usr/src/appEntry/start.sh"
      "${DB_PATH}" \
      "${DB_REPLICA_URL}"
else
  # Start server.
  eval "/usr/src/appEntry/start.sh"
fi